CREATE TABLE User( id INT NOT NULL AUTO_INCREMENT, username VARCHAR(32) NOT NULL, senha VARCHAR(32) NOT NULL, nickname VARCHAR(32),  PRIMARY KEY (ID) );

CREATE TABLE Notes ( id INT NOT NULL AUTO_INCREMENT, user_id INT NOT NULL REFERENCES User(id),  content VARCHAR(256) NOT NULL,  PRIMARY KEY (ID) );
